### PR TITLE
Styling changes, react 0.13.x, browserify + reactify ready

### PR DESCRIPTION
**Pull request by AVVS**
Nothing substantial besides what has been mentioned. Issue with multiple reacts is basically no longer an issue with current ver of react and modern browserify. One thing worth mentioning is dep on diaporama master. That might need to be changed when versions stabilize

### CODE REVIEW

**Comment by gre** [comment]
Hi AVVS ,
thanks for your contribution, that is a great simplification of the library.

However on my WIP diaporama-maker project, I still need to use this module with `react@0.12.x` because a few libraries I depends on are still requiring this version so I can't upgrade yet to 0.13.x. I hope this situation will be fixed soon, and I will probably contact the libraries authors.

```
npm ERR! peerinvalid Peer radium@0.10.0 wants react@0.12.x
npm ERR! peerinvalid Peer react-dnd@0.9.8 wants react@>=0.12.0 <0.14.0
```

However your fork seems to break when using with this older react version:

```
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null
Uncaught Error: Invariant Violation: findComponentRoot(..., .0.1.1.0.1): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

That is why I'm currently having this hacky code that inject React dependency via a function.

I don't really know if we can ever fix the 0.12.x/0.13.x issue and I think we should not spend much time on this, we can just support 0.13.x and all libraries will do in a few weeks.

Little detail: I would prefer the 2-spaces indenting.

PS: just FYI, I will improve the documentation of diaporama libs and related projects when I release the first diaporama-maker version very soon.

Best regards,
gre

**Comment by gre** [comment]
https://github.com/gaearon/react-dnd/issues/124
https://github.com/FormidableLabs/radium/issues/92

**Comment by gaearon** [comment]
NPM message sucks because it lists all peerDeps although _just one of them failed_.
It's `radium` locking in 0.12, not `react-dnd`.

**Comment by gre** [comment]
thanks @gaearon , you was right about this, and radium fortunately got up to date now.

@AVVS I'm going to merge your PR and also I'll probably put back the `react` dependency into `peerDependencies`.

**Pull request merged**
